name: Twitter Bot CI

on:
  push:
    paths:
      - twitter-bot/**
  pull_request:
    paths:
      - twitter-bot/**
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v3.1.0
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v3.0.5
        with:
          key: "$GITHUB_SHA"
          path: |
            ~/twitter-bot/builds
            ~/twitter-bot/build
            ~/twitter-bot/.gradle
      - name: Build with Gradle
        run: cd twitter-bot && ./gradlew compileKotlin
